import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";
import * as templates from "./templates/index.js";
import { banner, step, success, warn, info, done, dim, yellow } from "./ui.js";

export function migrate(dir = process.cwd()) {
  if (!existsSync(path.join(dir, ".logos"))) {
    console.error("Error: not a logos project (no .logos file found).");
    process.exit(1);
  }

  banner("migrate");

  console.log(`  ${yellow("⚗")} ${dim("experimental")}\n`);

  const migrateDir = path.join(dir, ".logos-migrate");
  mkdirSync(migrateDir, { recursive: true });

  // Write latest templates to migration directory
  step("Writing latest templates");
  writeFileSync(path.join(migrateDir, "AGENT.md"), templates.agentMd());
  writeFileSync(path.join(migrateDir, "CLAUDE.md"), templates.claudeMd());
  writeFileSync(path.join(migrateDir, "claude-settings.json"), templates.claudeSettings());
  writeFileSync(path.join(migrateDir, "readme-template.md"), templates.readmeMd("PROJECT"));
  writeFileSync(path.join(migrateDir, "gitignore"), templates.gitignore());
  success("Templates written to .logos-migrate/");

  // Read current versions for comparison
  const currentVersion = readVersion(dir);
  const pkgPath = path.resolve(
    path.dirname(new URL(import.meta.url).pathname),
    "../package.json"
  );
  const latestVersion = JSON.parse(readFileSync(pkgPath, "utf-8")).version;

  // Write migration instructions for the agent
  const instructions = buildInstructions(currentVersion, latestVersion);
  writeFileSync(path.join(migrateDir, "MIGRATE.md"), instructions);

  // Save current version
  writeFileSync(path.join(dir, ".logos"), latestVersion);

  done("Migration prepared");

  // Launch agent to apply migration
  step("Launching agent to apply migration");

  const prompt = "Read .logos-migrate/MIGRATE.md and follow every instruction in it. Do not ask for confirmation — just apply the migration, delete .logos-migrate/, and commit.";

  try {
    execSync(`claude "${prompt}"`, { cwd: dir, stdio: "inherit" });
  } catch {
    // Agent exited or not found
    warn("Could not launch agent automatically");
    info("Open your agent manually and say:");
    console.log();
    console.log(`  ${dim('"')}Follow the instructions in .logos-migrate/MIGRATE.md${dim('"')}`);
    console.log();
  }
}

function readVersion(dir) {
  try {
    const content = readFileSync(path.join(dir, ".logos"), "utf-8").trim();
    return content || null;
  } catch {
    return null;
  }
}

function buildInstructions(currentVersion, latestVersion) {
  return `# Logos Migration

> Generated by \`logos --migrate\`. This file tells you how to upgrade this project.
> Delete this entire \`.logos-migrate/\` directory when migration is complete.

## Versions

- **Current project version:** ${currentVersion || "unknown"}
- **Latest logos version:** ${latestVersion}

## Instructions

You are migrating an existing logos research project to the latest version. The \`.logos-migrate/\` directory contains the latest template files from logos v${latestVersion}.

**Rules:**
1. Never overwrite user content (agenda.md, setup.md, stages/, papers/, notes/, experiments/, data/)
2. AGENT.md and CLAUDE.md are logos-owned — replace them with the new versions from \`.logos-migrate/\`
3. For .claude/settings.json — merge the new config with any existing user settings (preserve user-added MCP servers, add any new ones from the template)
4. For README.md — the structure may have changed. Migrate the existing content into the new template structure. Preserve all user-written content (findings, status, paper lists) but adopt the new section layout
5. For .gitignore — merge, don't replace. Add any new entries from the template
6. After applying all changes, delete the \`.logos-migrate/\` directory
7. Commit with message: "chore: migrate to logos v${latestVersion}"

## Files to compare

| File | Action |
|------|--------|
| AGENT.md | Replace with \`.logos-migrate/AGENT.md\` |
| CLAUDE.md | Replace with \`.logos-migrate/CLAUDE.md\` |
| .claude/settings.json | Merge with \`.logos-migrate/claude-settings.json\` |
| README.md | Migrate content into new template from \`.logos-migrate/readme-template.md\` |
| .gitignore | Merge with \`.logos-migrate/gitignore\` |
`;
}
